### ISSUE TITLE
Filechooser.py Window' object has no attribute 'widget'

### ISSUE THREAD

**Issue by Inso-m-niaC** [nicotine-plus/nicotine-plus#3182]
Nicotine+ Version: 3.3.6
GTK Version: 4.16.3
Python Version: 3.11.10 (win32)

Type: <class 'AttributeError'>
Value: 'Window' object has no attribute 'widget'
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/widgets/filechooser.py", line 377, in on_open_file_chooser
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/widgets/filechooser.py", line 166, in present

```python
        self.metasettings = {
            "font_file": {
                "description": "Font File:",
                "type": "file",
                "chooser": "file"
            }
        }
```
Encountered after migrating from 3.2.9, so i am not sure when the bug was introduced.

**Comment by mathiascode** [comment]
Thanks! Looks like it broke in 3.3.0...
