### ISSUE TITLE
regression on open files on OpenBSD

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#536]
Whilst downloading multiple albums (5) I ran into:
```
Major Socket Error: Networking terminated! [Errno 24] Too many open files
```
And all my downloads stopped. Might this be a regression from #346

**Comment by hboetes** [comment]
Ah, there's even a trace with that:
```
Thu 14:11 Major Socket Error: Networking terminated! [Errno 24] Too many open
          files
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 1332, in updateLog
    AppendLine(self.LogWindow, msg, self.tag_log, scroll=shouldscroll)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/utils.py", line 428, in AppendLine
    va = scrolledwindow.get_vadjustment()
AttributeError: 'NoneType' object has no attribute 'get_vadjustment'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 1332, in updateLog
    AppendLine(self.LogWindow, msg, self.tag_log, scroll=shouldscroll)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/utils.py", line 428, in AppendLine
    va = scrolledwindow.get_vadjustment()
AttributeError: 'NoneType' object has no attribute 'get_vadjustment'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/frame.py", line 1332, in updateLog
    AppendLine(self.LogWindow, msg, self.tag_log, scroll=shouldscroll)
  File "/usr/local/lib/python3.7/site-packages/pynicotine/gtkgui/utils.py", line 428, in AppendLine
    va = scrolledwindow.get_vadjustment()
AttributeError: 'NoneType' object has no attribute 'get_vadjustment'
```

**Comment by mathiascode** [comment]
Thanks for the trace! It's unrelated, but sometimes occurs when the program is shutting down.

**Comment by hboetes** [comment]
Ah, OK. I should check the terminal before shutting down.
Can I remove the trace?

**Comment by mathiascode** [comment]
Keep it, it's also an issue I want to fix.

**Comment by hboetes** [comment]
will reopen when it happens again, but since it doesn't happen that often anyway, it's hard to reproduce.
